apiVersion: v1
kind: Secret
metadata:
  name: ycd-rke2-argocd
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: cluster
    environment: "dev"
type: Opaque
stringData:
  name: ycd-rke2
  server: "https://ycd-rke2.ycdisp.net:6443"
  config: |
    {
      "bearerToken": "eyJhbGciOiJSUzI1NiIsImtpZCI6IktXRDJOcFNwOWl0Vy1LN1VNcTdyaWMxWVNyYVdxZ0VXd09iUjJyUFhicjgifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJrdWJlLXN5c3RlbSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJhcmdvY2QtbWFuYWdlci10b2tlbiIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50Lm5hbWUiOiJhcmdvY2QtbWFuYWdlciIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50LnVpZCI6ImViMTQyYzZiLTUyNjItNGE2MC1hMjQwLWI0YTQyYjg2MmU1ZCIsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDprdWJlLXN5c3RlbTphcmdvY2QtbWFuYWdlciJ9.ls76K9vlpNhCcCuV8qe12EGQXDl9cMD9hZHaXZiupQuJefUxFmyW7J6hFkmUtwbA8PPY-yQNgK2dS83PRHrEaX2lypHUsyjSP7zv2EqJ3rk3xeiLjg6TKdKjb12PLUhloadevvPh_3D9zqdeU7-RoLc0hdw18QDzSpkzbNNG33fZQv7WhVniVMls-pqi5mKm3YyYfFmw-yzYuq42LjAx0wzSdbSEqmdDaNDK-G-Sqf1VlMYVvk6dD3XXFMm0tDibwUEZZfX2pREZRPSfDAEFGuaMNdYw1TzDmAGzyfXrhqD9-OIE0KDgePvWkZ-Kub1xVjoChy7vgXxuOo07F3LvbA",
      "tlsClientConfig": {
        "insecure": false,
        "caData": "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJlVENDQVIrZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQWtNU0l3SUFZRFZRUUREQmx5YTJVeUxYTmwKY25abGNpMWpZVUF4Tnprd01ESTVPRFV6TUI0WERUSTJNRGt5TVRJeE16QTFNMW9YRFRNMk1Ea3hPREl4TXpBMQpNMW93SkRFaU1DQUdBMVVFQXd3WmNtdGxNaTF6WlhKMlpYSXRZMkZBTVRjNU1EQXlPVGcxTXpCWk1CTUdCeXFHClNNNDlBZ0VHQ0NxR1NNNDlBd0VIQTBJQUJJRC8xMVFhNmlKekI5aVdYdUR0Sk9oYjBucUNmQWx4WWxpNEpSaWMKVTQ0Unp6bHBTVk02akprcGhsSkVzcFk5YXF3ajEvT3drN1RFSUJxdURORGdZSnFqUWpCQU1BNEdBMVVkRHdFQgovd1FFQXdJQ3BEQVBCZ05WSFJNQkFmOEVCVEFEQVFIL01CMEdBMVVkRGdRV0JCVGVZSHFwSlJ6cG5EdnpSNHB6Ci9ueDBzVVBkVURBS0JnZ3Foa2pPUFFRREFnTklBREJGQWlCQVVLZlQ3YTcza1RTTmVydmp0MFFqMDFUUUlsencKbHN6aE5iUGlnRWY1T3dJaEFLN3lFalNRbGYyS1d4NTRRdi9taFdBb1I0c0N5Z1dOTitEMUxwNDJPWDhMCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K"
      }
    }

      
