apiVersion: v1
kind: Secret
metadata:
  name: ycd-rke2-argocd
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: cluster
    environment: "dev"
type: Opaque
stringData:
  name: ycd-rke2
  server: "https://ycd-rke2.ycdisp.net:6443"
  config: |
    {
      "bearerToken": "{{ lookup('hashi_vault', 'secret=secret/ssh/ansible:ssh_password_bcrypt') }}",
      "tlsClientConfig": {
        "insecure": false,
        "caData": "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJlVENDQVIrZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQWtNU0l3SUFZRFZRUUREQmx5YTJVeUxYTmwKY25abGNpMWpZVUF4Tnprd01ESTVPRFV6TUI0WERUSTJNRGt5TVRJeE16QTFNMW9YRFRNMk1Ea3hPREl4TXpBMQpNMW93SkRFaU1DQUdBMVVFQXd3WmNtdGxNaTF6WlhKMlpYSXRZMkZBTVRjNU1EQXlPVGcxTXpCWk1CTUdCeXFHClNNNDlBZ0VHQ0NxR1NNNDlBd0VIQTBJQUJJRC8xMVFhNmlKekI5aVdYdUR0Sk9oYjBucUNmQWx4WWxpNEpSaWMKVTQ0Unp6bHBTVk02akprcGhsSkVzcFk5YXF3ajEvT3drN1RFSUJxdURORGdZSnFqUWpCQU1BNEdBMVVkRHdFQgovd1FFQXdJQ3BEQVBCZ05WSFJNQkFmOEVCVEFEQVFIL01CMEdBMVVkRGdRV0JCVGVZSHFwSlJ6cG5EdnpSNHB6Ci9ueDBzVVBkVURBS0JnZ3Foa2pPUFFRREFnTklBREJGQWlCQVVLZlQ3YTcza1RTTmVydmp0MFFqMDFUUUlsencKbHN6aE5iUGlnRWY1T3dJaEFLN3lFalNRbGYyS1d4NTRRdi9taFdBb1I0c0N5Z1dOTitEMUxwNDJPWDhMCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K"
      }
    }

      
