---
- name: Populate service facts
  ansible.builtin.service_facts:

- name: Copy kubernetes repository file
  ansible.builtin.copy:
    src: "kubernetes.repo"
    dest: "/etc/yum.repos.d/kubernetes.repo"
    mode: '0644'

- name: Create config directory - {{ k8s_dist }}
  ansible.builtin.file:
    path: "/etc/rancher/{{ k8s_dist }}/config.yaml.d"
    state: directory
    mode: '0755'
    recurse: true

- name: Copy kubelet config file
  ansible.builtin.copy:
    src: "kubelet.yaml"
    dest: "/etc/rancher/{{ k8s_dist }}/config.yaml.d/kubelet-limits.yaml"
    mode: '0644'

- name: Create base config on control plane nodes
  ansible.builtin.template:
    src: "{{ k8s_dist }}-cp-base.yaml.j2"
    dest: "/etc/rancher/{{ k8s_dist }}/config.yaml"
    mode: '0644'

- name: Copy Pod Security Standards config file
  ansible.builtin.copy:
    src: "pss.yaml"
    dest: "/etc/rancher/{{ k8s_dist }}/pss.yaml"
    mode: '0644'

- name: Create templated configs to control plane nodes - {{ k8s_dist }}
  ansible.builtin.template:
    src: "{{ template_file }}.j2"
    dest: "/etc/rancher/{{ k8s_dist }}/config.yaml.d/{{ template_file }}"
    mode: '0644'
  loop:
    - etcd.yaml
    - tls.yaml
    - networking.yaml
  loop_control:
    loop_var: template_file

- name: Taint control plane nodes for dedicated control plane setup - {{ k8s_dist }}
  when: hostvars['localhost']['dedicated_cp_nodes']
  ansible.builtin.copy:
    src: "{{ k8s_dist }}-cp-taint.yaml"
    dest: "/etc/rancher/{{ k8s_dist }}/config.yaml.d/cp-taint.yaml"
    mode: '0644'

- name: Set cluster init for first cp node - {{ k8s_dist }}
  when: inventory_hostname == hostvars['localhost']['cp_nodes'][0]
  ansible.builtin.lineinfile:
    path: "/etc/rancher/{{ k8s_dist }}/config.yaml"
    line: "cluster-init: true"
    insertafter: EOF

- name: Set server join for additional cp nodes - {{ k8s_dist }}
  when: inventory_hostname != hostvars['localhost']['cp_nodes'][0]
  ansible.builtin.lineinfile:
    path: "/etc/rancher/{{ k8s_dist }}/config.yaml"
    line: "server: https://{{ hostvars['localhost']['cp_nodes'][0] }}:9345"
    insertafter: EOF

- name: Insert token-file parameter
  ansible.builtin.lineinfile:
    path: "/etc/rancher/{{ k8s_dist }}/config.yaml"
    line: "token-file: /var/lib/rancher/{{ k8s_dist }}/server/node-token"
    insertafter: EOF

- name: Set token
  ansible.builtin.set_fact:
    rancher_token: "{{ lookup('hashi_vault', 'secret=secret/ssh/ansible:ssh_password') }}"

- name: Ensure node-token directory exists
  ansible.builtin.file:
    path: "/var/lib/rancher/{{ k8s_dist }}/server"
    state: directory
    mode: '0755'
    recurse: true

- name: Create node-token file
  ansible.builtin.copy:
    content: "{{ rancher_token }}"
    dest: "/var/lib/rancher/{{ k8s_dist }}/server/node-token"
    mode: '0600'

- name: Create vsphere_csi config file
  when: "'vsphere_csi' in hostvars['localhost']['base_components']"
  block:
    - name: Get VM ID
      delegate_to: localhost
      community.vmware.vmware_vm_info:
        hostname: "{{ hostvars['localhost']['vsphere_env'] }}"
        username: "{{ lookup('hashi_vault', 'secret/vsphere/vcsa:vsphere_username') }}"
        password: "{{ lookup('hashi_vault', 'secret/vsphere/vcsa:vsphere_password') }}"
        validate_certs: true
        vm_name: "{{ hostvars[inventory_hostname]['ansible_hostname'] }}"
      register: k8s_vm_info

    - name: Create vsphere-csi config file
      ansible.builtin.template:
        src: "vsphere-csi-cp.yaml.j2"
        dest: "/etc/rancher/{{ k8s_dist }}/config.yaml.d/vsphere-csi.yaml"
        mode: '0644'

- name: Create ingress-nginx config file
  when: "'ingress_nginx' in hostvars['localhost']['base_components']"
  ansible.builtin.copy:
    src: "ingress_nginx.yaml"
    dest: "/etc/rancher/{{ k8s_dist }}/config.yaml.d/ingress-nginx.yaml"
    mode: '0644'

- name: Download installer script - {{ k8s_dist }}
  when:
    - ansible_facts['services'][k8s_dist ~ '-server.service'] is not defined
  ansible.builtin.get_url:
    url: https://get.{{ k8s_dist }}.io
    dest: /tmp/{{ k8s_dist }}-installer.sh
    mode: '0755'

- name: Install K3S specific tasks
  when: >
    k8s_dist is defined and k8s_dist == 'k3s'
    and (ansible_facts['services'][k8s_dist ~ '-server.service'] is not defined
    or ansible_facts['services'][k8s_dist ~ '-server.service'].state != 'running')
  block:
    - name: Install K3S server
      ansible.builtin.shell: >
        set -eou pipefail &&
        /tmp/{{ k8s_dist }}-installer.sh
      environment:
        INSTALL_K3S_EXEC: "server"
        INSTALL_K3S_VERSION: "{{ k8s_ver }}"
      register: rancher_k8s_cp_install_status
      changed_when: rancher_k8s_cp_install_status.rc == 0

- name: Install RKE2 specific tasks
  when: >
    k8s_dist is defined and k8s_dist == 'rke2'
    and (ansible_facts['services'][k8s_dist ~ '-server.service'] is not defined
    or ansible_facts['services'][k8s_dist ~ '-server.service'].state != 'running')
  block:
    - name: Copy NetworkManager config file to host
      ansible.builtin.copy:
        src: "rke2-canal.conf"
        dest: "/etc/NetworkManager/conf.d/rke2-canal.conf"
        mode: '0644'

    - name: Restart NetworkManager asynchronously
      ansible.builtin.shell: >
        sleep 2 && systemctl restart NetworkManager
      async: 45
      poll: 0

    - name: Reset the SSH connection channel
      ansible.builtin.meta: reset_connection

    - name: Wait for the network interface to re-establish
      ansible.builtin.wait_for_connection:
        delay: 5
        timeout: 60

    - name: Install RKE2 server
      ansible.builtin.shell: >
        set -eou pipefail &&
        /tmp/{{ k8s_dist }}-installer.sh
      environment:
        INSTALL_RKE2_TYPE: "server"
        INSTALL_RKE2_VERSION: "{{ k8s_ver }}"
      register: rancher_k8s_cp_install_status
      changed_when: rancher_k8s_cp_install_status.rc == 0

- name: Enable service - {{ k8s_dist }}
  ansible.builtin.systemd_service:
    name: "{{ k8s_dist }}-server.service"
    enabled: true
    state: started
  retries: 10
  delay: 10
  register: rancher_k8s_service_status
  until: rancher_k8s_service_status is succeeded

- name: Wait until service is ready - {{ k8s_dist }}
  ansible.builtin.wait_for:
    host: localhost
    port: 6443
    delay: 10
    timeout: 300
    state: started
  register: rancher_k8s_ready
  until: rancher_k8s_ready is succeeded
